// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7tZLPt1ZZAMsRxkhIBFMT6oEdp6Hosg',
    appId: '1:592684899972:web:aa061882417cc8bf99ecd1',
    messagingSenderId: '592684899972',
    projectId: 'void-3ec18',
    authDomain: 'void-3ec18.firebaseapp.com',
    storageBucket: 'void-3ec18.firebasestorage.app',
    measurementId: 'G-KK5LSK853L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkeHDhtNUeZJ4fP5JmQF2959NVhkQ8QeU',
    appId: '1:592684899972:android:f8ce26e3258ef8c499ecd1',
    messagingSenderId: '592684899972',
    projectId: 'void-3ec18',
    storageBucket: 'void-3ec18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp5AKv8v0VtDzw9VIwro3JJbERFXmFKDQ',
    appId: '1:592684899972:ios:91a2027849f31d8b99ecd1',
    messagingSenderId: '592684899972',
    projectId: 'void-3ec18',
    storageBucket: 'void-3ec18.firebasestorage.app',
    iosBundleId: 'com.example.xVoid',
  );
}
